name: Fetch Event Media

on:
  workflow_dispatch: # 手动触发

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run media fetch
      env:
        BING_API_KEY: ${{ secrets.BING_API_KEY }}
        BING_API_ENDPOINT: ${{ secrets.BING_API_ENDPOINT }}
        SCREENSHOT_API_KEY: ${{ secrets.SCREENSHOT_API_KEY }}
      run: python fetch_media.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: media_results
        path: output/
